version: 0.2
        
phases:
 pre_build:
    commands:
      - echo pre-build
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - echo post-build

artifacts:
  files:
    - target/AboutProject.war
 